### ISSUE TITLE
system properties are not being picked up

### ISSUE THREAD

**Issue by mikesmithson** [Ardesco/Selenium-Maven-Template#14] opened 2015-09-18 13:59 UTC
I am not sure if it's me not understanding Failsafe but it appears that the system properties declared in the configuration section are not being recognized and the job fails. For example, I hardcoded

&lt;browser&gt;chrome&lt;/browser&gt; in the systemPropertyValues section and selenium was trying to invoke the Firefox webdriver. BTW - systemProperties is deprecated in favor systemPropertyValues.

**Comment by Ardesco** [comment] 2015-09-18 19:35
Seems to be working fine here if I change my POM to:

<?xml version="1.0" encoding="UTF-8"?>
    
    
    <project xmlns="http://maven.apache.org/POM/4.0.0"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    
        <groupId>com.lazerycode.selenium</groupId>
        <artifactId>maven-template</artifactId>
        <version>1.0-SNAPSHOT</version>
        <modelVersion>4.0.0</modelVersion>
    
        <name>Selenium Maven Template</name>
        <description>A Maven Template For Selenium</description>
        <url>http://www.lazerycode.com</url>
    
        <licenses>
            <license>
                <name>Apache 2</name>
                <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
                <distribution>repo</distribution>
                <comments>A business-friendly OSS license</comments>
            </license>
        </licenses>
    
        <properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
            <selenium.version>2.46.0</selenium.version>
            <overwrite.binaries>false</overwrite.binaries>
            <browser>firefox</browser>
            <threads>1</threads>
            <remote>false</remote>
            <seleniumGridURL/>
            <platform/>
            <browserVersion/>
            <proxyEnabled>false</proxyEnabled>
            <proxyHost/>
            <proxyPort/>
        </properties>
    
        <dependencies>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>1.3</version>
            </dependency>
            <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>${selenium.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-remote-driver</artifactId>
                <version>${selenium.version}</version>
            </dependency>
            <dependency>
                <groupId>com.codeborne</groupId>
                <artifactId>phantomjsdriver</artifactId>
                <version>1.2.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>6.9.6</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    
        <profiles>
            <profile>
                <id>selenium-tests</id>
                <activation>
                    <activeByDefault>true</activeByDefault>
                </activation>
                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <configuration>
                                <source>1.7</source>
                                <target>1.7</target>
                            </configuration>
                            <version>2.3.2</version>
                        </plugin>
                        <plugin>
                            <groupId>com.lazerycode.selenium</groupId>
                            <artifactId>driver-binary-downloader-maven-plugin</artifactId>
                            <version>1.0.7</version>
                            <configuration>
                                <rootStandaloneServerDirectory>${standalone.binary.root.folder}</rootStandaloneServerDirectory>
                                <downloadedZipFileDirectory>${project.basedir}/src/test/resources/selenium_standalone_zips</downloadedZipFileDirectory>
                                <customRepositoryMap>${project.basedir}/src/test/resources/RepositoryMap.xml</customRepositoryMap>
                                <overwriteFilesThatExist>${overwrite.binaries}</overwriteFilesThatExist>
                            </configuration>
                            <executions>
                                <execution>
                                    <goals>
                                        <goal>selenium</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-failsafe-plugin</artifactId>
                            <version>2.18.1</version>
                            <configuration>
                                <parallel>methods</parallel>
                                <threadCount>${threads}</threadCount>
                                <systemPropertyVariables>
                                    <browser>chrome</browser>
                                    <screenshotDirectory>${project.build.directory}/screenshots</screenshotDirectory>
                                    <remoteDriver>${remote}</remoteDriver>
                                    <gridURL>${seleniumGridURL}</gridURL>
                                    <desiredPlatform>${platform}</desiredPlatform>
                                    <desiredBrowserVersion>${browserVersion}</desiredBrowserVersion>
                                    <proxyEnabled>${proxyEnabled}</proxyEnabled>
                                    <proxyHost>${proxyHost}</proxyHost>
                                    <proxyPort>${proxyPort}</proxyPort>
    
                                    
                                    <phantomjs.binary.path>${phantomjs.binary.path}</phantomjs.binary.path>
                                    <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                                    <webdriver.ie.driver>${webdriver.ie.driver}</webdriver.ie.driver>
                                    <webdriver.opera.driver>${webdriver.opera.driver}</webdriver.opera.driver>
                                </systemPropertyVariables>
                                <includes>
                                    <include>**/*WebDriver.java</include>
                                </includes>
                            </configuration>
                            <executions>
                                <execution>
                                    <goals>
                                        <goal>integration-test</goal>
                                        <goal>verify</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </build>
            </profile>
        </profiles>
    </project>

**Comment by Ardesco** [comment] 2015-09-18 19:36
What version of Maven are you using?

I'm on:

    mvn -v
    Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:37+01:00)
    Maven home: /usr/local/Cellar/maven/3.3.3/libexec
    Java version: 1.8.0_25, vendor: Oracle Corporation
    Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

**Comment by Ardesco** [comment] 2015-09-20 14:21
Can you double check that you are using `<systemPropertyVariables>` and not `< systemPropertyValues >` as stated in your original comment.  That's the only potential problem I can find at the moment.

**Comment by rombow** [comment] 2015-09-30 13:14
Hm i have almost same problem. If i have one new test class "FistTest.java" near GoogleExampleWebDriver.java then it seems failsafe plugin not fired and system properties not setted...

**Comment by Ardesco** [comment] 2015-09-30 14:35
This is by design.  The maven failsafe plugin configuration has this setting:

    <includes>
        <include>**/*WebDriver.java</include>
    </includes>

This means that it will only pick up test files that end in `WebDriver.java`.  It works if you change your class name to `FistTestWebDriver.java` as you have already noted.  You can change the config to this:

    <includes>
        <include>**/*Test.java</include>
    </includes>

Then it will pick up `FistTest.java`.  The reason that I'm not using `**/*Test.java` by default is that usually unit tests will have Test in the name.  These are generally picked up by maven surefire plugin and run in the test phase rather than the integration-test phase.  We don't want our WebDriver tests to be picked up and run with the unit tests which is why we use a different naming pattern.  If ending every test with WebDriver.java is too verbose you can tweak it and change it to anything you want.  In the real world I normally use:

    <includes>
        <include>**/*WD.java</include>
    </includes>

I've just used the full name in this template for clarity.

**Comment by rombow** [comment] 2015-09-30 14:53
Yes i know how its working, i said only if you set in your pom.xml
```xml
<includes>
    <include>**/*Test.java</include>
</includes>
```
and rename GoogleExampleWebDriver.java to GoogleExampleWebDriverTest.java then failsafe not fired (only surefire, but surefire not seting system properties). Actually failsafe is not firing if any *Test.java file exists does't not matter failsafe config

**Comment by Ardesco** [comment] 2015-09-30 20:07
By default the maven-surefire-plugin will pick up all tests ending in `**/*Test.java`.  If the maven-surefire-plugin runs the tests, the maven-failsafe-plugin will not then run them as well.  If you don't want the maven-surefire-plugin to pick up things with the `**/*Test.java` file pattern you can configure surefire to ignore them by tweaking the surefire config like so:

    <configuration>
        <excludes>
            <exclude>**/*Test.java</exclude>
        </excludes>
    </configuration>

or if you are using TestNG tests in failsafe and jUnit tests in surefire you could try this configuration option for the maven-surefire-plugin:

    <configuration>
        <testNGArtifactName>none:none</testNGArtifactName >
    </configuration>

Both of these are a pain which is why by default I don't use the `**/*Test.java` file pattern for WebDriver tests in the template, I configure a file pattern which the maven-surefire-plugin will not pick up, and the maven-failsafe plugin will.  It should be noted that by default the maven-failsafe-plugin uses the following file paths:

    <configuration>
        <includes>
            <include>**/IT*.java</include>
            <include>**/*IT.java</include>
            <include>**/*ITCase.java</include>
        </includes>
    </configuration>

So you could just change your test names to use one of these file patterns.  When this template was originally written it didn't use the maven-failsafe-plugin so I didn't use GoogleExampleIT.java, instead I created my own file pattern and it's stuck.

If you do want to run the tests in the maven-surefire-plugin instead of the maven-failsafe-plugin, (which I don't recommend because they will then run in the test phase rather than the integration-test phase) you can just copy the maven-failsafe-plugin configuration and use it on the maven-surefire-plugin.  It would then look like this:

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.18.1</version>
        <configuration>
            <parallel>methods</parallel>
            <threadCount>${threads}</threadCount>
            <systemPropertyVariables>
                <browser>${browser}</browser>
                <screenshotDirectory>${project.build.directory}/screenshots</screenshotDirectory>
                <remoteDriver>${remote}</remoteDriver>
                <gridURL>${seleniumGridURL}</gridURL>
                <desiredPlatform>${platform}</desiredPlatform>
                <desiredBrowserVersion>${browserVersion}</desiredBrowserVersion>
                <proxyEnabled>${proxyEnabled}</proxyEnabled>
                <proxyHost>${proxyHost}</proxyHost>
                <proxyPort>${proxyPort}</proxyPort>

                
                <phantomjs.binary.path>${phantomjs.binary.path}</phantomjs.binary.path>
                <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                <webdriver.ie.driver>${webdriver.ie.driver}</webdriver.ie.driver>
                <webdriver.opera.driver>${webdriver.opera.driver}</webdriver.opera.driver>
            </systemPropertyVariables>
            <includes>
                <include>**/*WebDriver.java</include>
            </includes>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>test</goal>
                </goals>
            </execution>
        </executions>
    </plugin>

I hope this helps, hopefully I've provided some in depth explanation of how it all hangs together.

**Comment by rombow** [comment] 2015-10-01 08:13
Oh i finally find whats i doing wrong. My "FirstTest" are fail test to testing screenshot making in selenium. This test running with surefire plugin in "test" maven phase (by default "*Test" name). Because this phase failed, "integration-test" maven phase not fired for failsafe plugin and thats why "*WebDriver" not running...

Thanks for detail explanation and patience!

**Comment by Ardesco** [comment] 2015-10-14 22:13
I'm going to close this as I've not heard anything back about the original problem.  I'm going to need a failing example to do any more if all of the above has not resolved the issue.

**Closed by Ardesco** 2015-10-14 22:13 UTC
Labels: invalid
